export interface CaseStudy {
  slug: string;
  client: string;
  category: "ai" | "automation" | "data" | "development" | "ecommerce" | "b2b";
  image: string;
  metric: string;
  tr: { title: string; excerpt: string; challenge: string; solution: string; result: string };
  en: { title: string; excerpt: string; challenge: string; solution: string; result: string };
  nl: { title: string; excerpt: string; challenge: string; solution: string; result: string };
}

export const caseStudies: CaseStudy[] = [
  {
    slug: "boutiquerugs",
    client: "BoutiqueRugs",
    category: "ecommerce",
    image: "/images/industry-ecommerce.jpg",
    metric: "46%",
    tr: {
      title: "E-ticaret AR Ürün Görselleştirme",
      excerpt: "BoutiqueRugs için AR tabanlı ürün görselleştirme ile sepet terk oranında %46 düşüş sağlandı.",
      challenge: "Müşteriler online halı alışverişinde ürünleri evlerinde nasıl duracağını göremiyordu, bu da yüksek sepet terk oranlarına yol açıyordu.",
      solution: "AR tabanlı ürün görselleştirme platformu geliştirdik. Müşteriler telefonlarının kamerasını kullanarak halıları kendi evlerinde görebildi.",
      result: "Sepet terk oranı %46 azaldı, dönüşüm oranı %32 arttı ve müşteri memnuniyeti rekor seviyeye ulaştı.",
    },
    en: {
      title: "E-commerce AR Product Visualization",
      excerpt: "Achieved 46% reduction in cart abandonment through AR-based product visualization for BoutiqueRugs.",
      challenge: "Customers couldn't visualize how rugs would look in their homes during online shopping, leading to high cart abandonment rates.",
      solution: "We developed an AR-based product visualization platform. Customers could use their phone cameras to see rugs in their actual living spaces.",
      result: "Cart abandonment dropped by 46%, conversion rate increased by 32%, and customer satisfaction reached record levels.",
    },
    nl: {
      title: "E-commerce AR Productvisualisatie",
      excerpt: "46% minder winkelwagenverlating door AR-gebaseerde productvisualisatie voor BoutiqueRugs.",
      challenge: "Klanten konden niet zien hoe tapijten er in hun huis uit zouden zien bij online winkelen, wat leidde tot hoge winkelwagenverlatingspercentages.",
      solution: "We ontwikkelden een AR-gebaseerd productvisualisatieplatform. Klanten konden hun telefoon gebruiken om tapijten in hun eigen woonruimtes te bekijken.",
      result: "Winkelwagenverlating daalde met 46%, het conversiepercentage steeg met 32% en de klanttevredenheid bereikte recordniveaus.",
    },
  },
  {
    slug: "westwing",
    client: "Westwing",
    category: "b2b",
    image: "/images/industry-retail.jpg",
    metric: "€65K+",
    tr: {
      title: "B2B Satış Otomasyonu",
      excerpt: "Westwing ile B2B satış otomasyonu sayesinde €65.000+ gelir elde edildi.",
      challenge: "Westwing'in B2B satış süreçleri manuel ve zaman alıcıydı, potansiyel müşterilere ulaşmak yavaş kalıyordu.",
      solution: "AI destekli satış otomasyonu ve müşteri segmentasyonu ile kişiselleştirilmiş outreach kampanyaları oluşturduk.",
      result: "€65.000+ direkt gelir, satış döngüsü %40 kısaldı ve müşteri kazanım maliyeti %35 düştü.",
    },
    en: {
      title: "B2B Sales Automation Pipeline",
      excerpt: "Generated €65,000+ revenue through B2B sales automation for Westwing.",
      challenge: "Westwing's B2B sales processes were manual and time-consuming, with slow outreach to potential clients.",
      solution: "We created AI-powered sales automation and customer segmentation with personalized outreach campaigns.",
      result: "€65,000+ direct revenue generated, sales cycle shortened by 40%, and customer acquisition cost dropped by 35%.",
    },
    nl: {
      title: "B2B Verkoopautomatisering",
      excerpt: "€65.000+ omzet gegenereerd door B2B-verkoopautomatisering voor Westwing.",
      challenge: "De B2B-verkoopprocessen van Westwing waren handmatig en tijdrovend, met trage bereikbaarheid van potentiële klanten.",
      solution: "We creëerden AI-aangedreven verkoopautomatisering en klantsegmentatie met gepersonaliseerde outreachcampagnes.",
      result: "€65.000+ directe omzet gegenereerd, verkoopscyclus met 40% verkort en klantwervingskosten met 35% gedaald.",
    },
  },
  {
    slug: "tolon",
    client: "Tolon",
    category: "b2b",
    image: "/images/industry-manufacturing.jpg",
    metric: "410",
    tr: {
      title: "Pazar Lideri Müşteri Kazanımı",
      excerpt: "80 yıllık pazar lideri Tolon için 410 nitelikli müşteri kazanıldı.",
      challenge: "Tolon, geleneksel satış yöntemleriyle yeni pazarlara ulaşmakta zorlanıyordu.",
      solution: "AI destekli prospect belirleme ve otomatik outreach kampanyaları ile hedefli müşteri kazanım stratejisi uyguladık.",
      result: "410 nitelikli müşteri kazanıldı, pazar payı %15 arttı ve satış ekibinin verimliliği ikiye katlandı.",
    },
    en: {
      title: "Market Leader Customer Acquisition",
      excerpt: "Acquired 410 qualified customers for 80-year market leader Tolon.",
      challenge: "Tolon struggled to reach new markets using traditional sales methods.",
      solution: "We implemented an AI-powered prospect identification and automated outreach campaign with targeted customer acquisition strategy.",
      result: "410 qualified customers acquired, market share grew by 15%, and sales team efficiency doubled.",
    },
    nl: {
      title: "Marktleider Klantwerving",
      excerpt: "410 gekwalificeerde klanten geworven voor 80-jarige marktleider Tolon.",
      challenge: "Tolon had moeite om nieuwe markten te bereiken met traditionele verkoopmethoden.",
      solution: "We implementeerden AI-aangedreven prospectidentificatie en geautomatiseerde outreachcampagnes met gerichte klantwervingsstrategie.",
      result: "410 gekwalificeerde klanten geworven, marktaandeel groeide met 15% en de efficiëntie van het verkoopteam verdubbelde.",
    },
  },
  {
    slug: "naz-teknik",
    client: "Naz Teknik",
    category: "automation",
    image: "/images/industry-logistics.jpg",
    metric: "850",
    tr: {
      title: "Yurt İçi Pazar Erişimi Genişletme",
      excerpt: "Naz Teknik için otomasyon ile 850 nitelikli müşteriye ulaşıldı.",
      challenge: "Naz Teknik'in yurt içi pazarda marka bilinirliği düşüktü ve müşteri tabanını genişletmekte zorlanıyordu.",
      solution: "Otomatik satış kampanyaları ve AI destekli müşteri hedefleme ile yurt içi pazar penetrasyon stratejisi oluşturduk.",
      result: "850 nitelikli müşteri kazanıldı, marka bilinirliği %60 arttı ve aylık satışlar 3 katına çıktı.",
    },
    en: {
      title: "Domestic Market Reach Expansion",
      excerpt: "Reached 850 qualified customers through automation for Naz Teknik.",
      challenge: "Naz Teknik had low brand awareness in the domestic market and struggled to expand its customer base.",
      solution: "We created automated sales campaigns and AI-powered customer targeting with a domestic market penetration strategy.",
      result: "850 qualified customers acquired, brand awareness increased by 60%, and monthly sales tripled.",
    },
    nl: {
      title: "Uitbreiding Binnenlands Marktbereik",
      excerpt: "850 gekwalificeerde klanten bereikt door automatisering voor Naz Teknik.",
      challenge: "Naz Teknik had een lage merkbekendheid op de binnenlandse markt en had moeite met het uitbreiden van het klantenbestand.",
      solution: "We creëerden geautomatiseerde verkoopcampagnes en AI-aangedreven klantdoelgroepbepaling met een binnenlandse marktpenetratiestrategie.",
      result: "850 gekwalificeerde klanten geworven, merkbekendheid steeg met 60% en de maandelijkse verkoop verdrievoudigde.",
    },
  },
  {
    slug: "arkman",
    client: "Arkman",
    category: "b2b",
    image: "/images/industry-finance.jpg",
    metric: "151",
    tr: {
      title: "Pazar Payı Genişletme",
      excerpt: "Arkman için 151 nitelikli müşteri ile pazar payı genişletildi.",
      challenge: "Arkman rekabetçi pazarda büyüme sağlamakta ve yeni müşteriler bulmakta zorlanıyordu.",
      solution: "25+ milyon şirket veri tabanından hedefli prospect belirleme ve kişiselleştirilmiş mesajlaşma stratejisi uyguladık.",
      result: "151 nitelikli müşteri kazanıldı, pazar payı genişledi ve müşteri başına gelir %25 arttı.",
    },
    en: {
      title: "Market Share Expansion",
      excerpt: "Expanded market share with 151 qualified customers for Arkman.",
      challenge: "Arkman struggled to grow in a competitive market and find new customers.",
      solution: "We implemented targeted prospect identification from a database of 25+ million companies with personalized messaging strategy.",
      result: "151 qualified customers acquired, market share expanded, and revenue per customer increased by 25%.",
    },
    nl: {
      title: "Uitbreiding Marktaandeel",
      excerpt: "Marktaandeel uitgebreid met 151 gekwalificeerde klanten voor Arkman.",
      challenge: "Arkman had moeite om te groeien in een concurrerende markt en nieuwe klanten te vinden.",
      solution: "We implementeerden gerichte prospectidentificatie uit een database van 25+ miljoen bedrijven met gepersonaliseerde berichtenstrategie.",
      result: "151 gekwalificeerde klanten geworven, marktaandeel uitgebreid en omzet per klant steeg met 25%.",
    },
  },
  {
    slug: "yena",
    client: "YENA",
    category: "automation",
    image: "/images/industry-manufacturing.jpg",
    metric: "3x",
    tr: {
      title: "Üretim B2B Otomasyonu",
      excerpt: "YENA Engineering için üretim süreçlerinde 3 kat verimlilik artışı sağlandı.",
      challenge: "YENA'nın kaynaklı imalat süreçlerinde müşteri ilişkileri yönetimi ve sipariş takibi manuel olarak yapılıyordu.",
      solution: "CRM entegrasyonu ve otomatik sipariş yönetim sistemi kurarak B2B satış süreçlerini dijitalleştirdik.",
      result: "Verimlilik 3 katına çıktı, sipariş işleme süresi %70 azaldı ve müşteri memnuniyeti %45 arttı.",
    },
    en: {
      title: "Manufacturing B2B Automation",
      excerpt: "Achieved 3x efficiency improvement in manufacturing processes for YENA Engineering.",
      challenge: "YENA's welded manufacturing processes relied on manual CRM and order tracking.",
      solution: "We digitalized B2B sales processes with CRM integration and automated order management systems.",
      result: "3x efficiency improvement, order processing time reduced by 70%, and customer satisfaction increased by 45%.",
    },
    nl: {
      title: "Productie B2B-automatisering",
      excerpt: "3x efficiëntieverbetering in productieprocessen voor YENA Engineering.",
      challenge: "De gelaste productieprocessen van YENA waren afhankelijk van handmatige CRM en ordertracking.",
      solution: "We digitaliseerden B2B-verkoopprocessen met CRM-integratie en geautomatiseerde ordermanagementsystemen.",
      result: "3x efficiëntieverbetering, orderverwerkingstijd met 70% verminderd en klanttevredenheid met 45% gestegen.",
    },
  },
  {
    slug: "steps-agency",
    client: "Steps Agency",
    category: "automation",
    image: "/images/industry-hr.jpg",
    metric: "100+",
    tr: {
      title: "B2B Pazarlama Otomasyonu",
      excerpt: "Steps Agency için 100+ nitelikli müşteri kazanıldı.",
      challenge: "Steps Agency'nin B2B müşteri kazanımı tamamen manuel süreçlere dayanıyordu.",
      solution: "Otomatik pazarlama kampanyaları ve lead scoring sistemi ile dijital müşteri kazanım stratejisi oluşturduk.",
      result: "100+ nitelikli müşteri kazanıldı, pazarlama maliyetleri %40 düştü ve lead kalitesi %55 arttı.",
    },
    en: {
      title: "B2B Marketing Automation",
      excerpt: "Acquired 100+ qualified customers for Steps Agency through marketing automation.",
      challenge: "Steps Agency's B2B customer acquisition relied entirely on manual processes.",
      solution: "We created automated marketing campaigns and a lead scoring system with a digital customer acquisition strategy.",
      result: "100+ qualified customers acquired, marketing costs dropped by 40%, and lead quality improved by 55%.",
    },
    nl: {
      title: "B2B Marketingautomatisering",
      excerpt: "100+ gekwalificeerde klanten geworven voor Steps Agency door marketingautomatisering.",
      challenge: "De B2B-klantwerving van Steps Agency was volledig afhankelijk van handmatige processen.",
      solution: "We creëerden geautomatiseerde marketingcampagnes en een lead scoring-systeem met een digitale klantwervingsstrategie.",
      result: "100+ gekwalificeerde klanten geworven, marketingkosten daalden met 40% en leadkwaliteit verbeterde met 55%.",
    },
  },
  {
    slug: "steelify",
    client: "Steelify",
    category: "automation",
    image: "/images/industry-manufacturing.jpg",
    metric: "70%",
    tr: {
      title: "Üretim Süreç Otomasyonu",
      excerpt: "Steelify için üretim süreçlerinde %70 verimlilik artışı sağlandı.",
      challenge: "Steelify'ın çelik üretim süreçlerinde kalite kontrol ve sipariş yönetimi yavaş ve hataya açıktı.",
      solution: "AI destekli kalite kontrol ve otomatik sipariş yönetim sistemi kurarak süreçleri optimize ettik.",
      result: "Verimlilik %70 arttı, hata oranı %85 azaldı ve teslimat süreleri %50 kısaldı.",
    },
    en: {
      title: "Manufacturing Process Automation",
      excerpt: "Achieved 70% efficiency improvement in production processes for Steelify.",
      challenge: "Steelify's steel production processes had slow quality control and error-prone order management.",
      solution: "We optimized processes with AI-powered quality control and automated order management systems.",
      result: "70% efficiency improvement, error rate reduced by 85%, and delivery times shortened by 50%.",
    },
    nl: {
      title: "Productie Procesautomatisering",
      excerpt: "70% efficiëntieverbetering in productieprocessen voor Steelify.",
      challenge: "De staalproductieprocessen van Steelify hadden trage kwaliteitscontrole en foutgevoelig orderbeheer.",
      solution: "We optimaliseerden processen met AI-aangedreven kwaliteitscontrole en geautomatiseerde ordermanagementsystemen.",
      result: "70% efficiëntieverbetering, foutpercentage met 85% verminderd en levertijden met 50% verkort.",
    },
  },
  {
    slug: "tuva-home",
    client: "Tuva Home",
    category: "ecommerce",
    image: "/images/industry-ecommerce.jpg",
    metric: "2.5x",
    tr: {
      title: "E-ticaret Optimizasyonu",
      excerpt: "Tuva Home için e-ticaret satışları 2.5 katına çıkarıldı.",
      challenge: "Tuva Home'un online satış kanalı düşük dönüşüm oranları ve yüksek müşteri kaybı ile mücadele ediyordu.",
      solution: "AI destekli ürün önerileri, otomatik kampanya yönetimi ve kişiselleştirilmiş müşteri deneyimi platformu kurduk.",
      result: "Satışlar 2.5 katına çıktı, dönüşüm oranı %80 arttı ve müşteri yaşam boyu değeri %60 yükseldi.",
    },
    en: {
      title: "E-commerce Optimization",
      excerpt: "Increased e-commerce sales by 2.5x for Tuva Home.",
      challenge: "Tuva Home's online sales channel struggled with low conversion rates and high customer churn.",
      solution: "We built AI-powered product recommendations, automated campaign management, and a personalized customer experience platform.",
      result: "Sales increased 2.5x, conversion rate improved by 80%, and customer lifetime value rose by 60%.",
    },
    nl: {
      title: "E-commerce Optimalisatie",
      excerpt: "E-commerce verkoop met 2,5x verhoogd voor Tuva Home.",
      challenge: "Het online verkoopkanaal van Tuva Home had last van lage conversiepercentages en hoog klantverloop.",
      solution: "We bouwden AI-aangedreven productaanbevelingen, geautomatiseerd campagnebeheer en een gepersonaliseerd klantenervaringplatform.",
      result: "Verkoop met 2,5x verhoogd, conversiepercentage met 80% verbeterd en klantlevensduurwaarde met 60% gestegen.",
    },
  },
];

export const caseCategories = [
  { value: "all", label: "All" },
  { value: "ai", label: "AI" },
  { value: "automation", label: "Automation" },
  { value: "b2b", label: "B2B" },
  { value: "ecommerce", label: "E-commerce" },
  { value: "data", label: "Data" },
  { value: "development", label: "Development" },
];
